In [1]:
%serialconnect to --port="/dev/tty.usbserial-02EDKZTP" --baud=115200

Connecting to --port=/dev/tty.usbserial-02EDKZTP --baud=115200 
MicroPython v1.14 on 2021-04-12; ESP32 module with ESP32
Type "help()" for more information.
>>>[reboot detected 0]repl is in normal command mode
[\r\x03\x03] b'\r\n>>> '
[\r\x01] b'\r\n>>> \r\nraw REPL; CTRL-B to exit\r\n>' Ready.


In [2]:
from ulab import numpy as np
import machine
from machine import Pin, PWM

In [3]:
import utime

led = Pin(22, Pin.OUT)

for i in range(10):
    led.on()
    utime.sleep(0.1)
    led.off()
    utime.sleep(0.1)

In [4]:
# X correlation matrix
Cxx = np.array([[166.14279703,  99.48821575,  24.11370662, -33.37944544],
       [ 99.48821575, 166.12703417,  90.66107192,  71.18545196],
       [ 24.11370662,  90.66107192, 166.83747439,  66.71419887],
       [-33.37944544,  71.18545196,  66.71419887, 166.71542984]])

# Y correlation matrix
Cyy = np.array([[167.        ,   0.43605292,   1.06028619,  -0.1970634 ],
       [  0.43605292, 167.        ,   0.41206453,  -0.69571169],
       [  1.06028619,   0.41206453, 167.        ,  -5.19137319],
       [ -0.1970634 ,  -0.69571169,  -5.19137319, 167.        ]])

# XY cross-correlation matrix
Cxy = np.array([[18.49359001, -0.09579883, -1.47948752,  5.81688046],
       [ 9.60223537,  7.45818488, -1.80016572,  7.20337205],
       [17.57176942, -8.21102309, -0.50311062,  1.26140711],
       [-4.71848465, 15.03455974, -0.45756603,  1.86271787]])

In [5]:
M1 = np.dot(np.linalg.inv(Cxx), Cxy)
M2 = np.dot(np.linalg.inv(Cyy), Cxy.transpose())
M = np.dot(M1, M2)
print(M)

array([[0.01751957, 0.009391238, 0.01634465, -0.004151698],
       [-0.01062538, -0.001212584, -0.01466249, 0.009756293],
       [0.0156384, 0.001652602, 0.02181821, -0.01627565],
       [-0.001002286, 0.004650325, -0.00654409, 0.010586]], dtype=float32)


In [7]:
Cxx_isqrt = np.linalg.inv(np.linalg.cholesky(Cxx))
Cyy_isqrt = np.linalg.inv(np.linalg.cholesky(Cyy))
Omega = np.dot(np.dot(Cxx_isqrt, Cxy), Cyy_isqrt)

print(Omega)

array([[0.1111172, -0.0004105715, -0.007796702, 0.03493855],
       [-0.01111094, 0.05647156, -0.005986812, 0.027902],
       [0.1184806, -0.1007652, 0.002194773, -0.016655],
       [-0.005966277, 0.08029782, 4.725839e-05, -0.0001810153]], dtype=float32)


In [8]:
print(np.linalg.eig(np.dot(Omega, Omega.transpose())))


(array([0.01113427, 2.507131e-07, 0.03670151, 0.0008763761], dtype=float32), array([[0.7310294, -0.4112509, 0.455054, -0.298989],
       [0.4303756, 0.7863671, -0.2297222, -0.3789873],
       [-0.1077175, 0.4604145, 0.812761, 0.3403455],
       [0.5184302, 0.02275724, -0.2820871, 0.806932]], dtype=float32))


In [20]:
%lsmagic

%capture [--quiet] [--QUIET] outputfilename
    records output to a file

%comment
    print this into output

%disconnect [--raw]
    disconnects from web/serial connection

%esptool [--port PORT] {erase,esp32,esp8266} [binfile]
    commands for flashing your esp-device

%fetchfile [--binary] [--print] [--load] [--quiet] [--QUIET]
                  sourcefilename [destinationfilename]
    fetch and save a file from the device

%ls [--recurse] [dirname]
    list files on the device

%lsmagic
    list magic commands

%mpy-cross [--set-exe SET_EXE] [pyfile]
    cross-compile a .py file to a .mpy file

%readbytes [--binary]
    does serial.read_all()

%rebootdevice
    reboots device

%sendtofile [--append] [--mkdir] [--binary] [--execute] [--source [SOURCE]] [--quiet]
                   [--QUIET]
                   [destinationfilename]
    send cell contents or file/direcectory to the device

%serialconnect [--raw] [--port PORT] [--baud BAUD] [--verbose]
    connects to a device over US